<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 1</b></center>    
<pre>    

# NumPy Exercises
## We'll start off with a few simple tasks

## import numpy as np

### What is NumPy? (5 Key Points)

1. **Core Purpose**: NumPy (Numerical Python) is the foundational library for numerical and scientific computing in Python.
2. **N-Dimensional Arrays (`ndarray`)**: Its central feature is the powerful, highly efficient multidimensional array object. Unlike standard Python lists, these arrays hold items of the same type and allow for fast, vectorized mathematical operations.
3. **High Performance**: Because its core operations are implemented in C, NumPy is incredibly fast. It executes complex computations on large datasets much more efficiently than standard Python loops and lists.
4. **Rich Mathematical Toolkit**: It provides a vast collection of built-in mathematical, logical, shape manipulation, sorting, and basic statistical operations that can be applied to entire arrays without needing explicit loops.
5. **Foundation of the Ecosystem**: NumPy serves as the bedrock for almost the entire Python data science and machine learning ecosystem. Popular libraries like Pandas, SciPy, scikit-learn, and TensorFlow are built on top of it or rely heavily on its array structures.


In [1]:
import numpy as np

In [2]:
n = np.array([1,2,3,4],dtype=str)

In [3]:
type(n)

numpy.ndarray

In [4]:
n

array(['1', '2', '3', '4'], dtype='<U1')

In [5]:
n.dtype

dtype('<U1')

## Create an array of 10 zeros

In [6]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Create an array of 10 ones

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Create an array of 10 fives

In [9]:
np.ones(10) *5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## Create an array of the integers from 10 to 50

In [10]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
np.arange(0,9,1).reshape(1,9)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

## Create a 3x3 identity matrix

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create following matrix  = <br/>
<pre>array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])</pre>

In [13]:
n =np.arange(1,26,1).reshape(5,5)

## Output should be =
<pre>array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])</pre>

In [14]:
n[2::,1::]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

## Output should be = <br/>
<pre>array([[ 2],
       [ 7],
       [12]])</pre>

In [15]:
n[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

## Find Odd Numbers
Extract all odd numbers from `arr`.

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` <BR>
Use Condtional Selection

In [16]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 == 1]
print(odd_numbers)

[1 3 5 7 9]


## Stacking
Stack array `a` and `b` vertically.

`a = np.arange(10).reshape(2,-1)`
`b = np.repeat(1, 10).reshape(2,-1)`

In [17]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
output = np.vstack([a, b])
print(output)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3, 4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##  Range Filtering
Get all items between 5 and 10 from `a`.

`a = np.array([2, 6, 1, 9, 10, 3, 27])`

In [19]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
output = a[(a >= 5) & (a <= 10)]
print(output)

[ 6  9 10]


## Matrix Multiplication
Multiply a 5x3 matrix by a 3x2 matrix (dot product).

In [20]:
A = np.random.random((5,3))
B = np.random.random((3,2))
product = np.dot(A, B)
print(product)

[[0.87216213 0.66803398]
 [0.76091908 0.24521162]
 [0.83806596 0.7118518 ]
 [0.73222425 0.6410209 ]
 [0.72162042 0.44485617]]


# Great Job! You’re Halfway Through 🚀  | PANDAS  Exercises



### Step 1. Import the necessary libraries

In [31]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [33]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")
df

,user_id,age,gender,occupation,zip_code
0,1,24,M,technician,85711
1,2,53,F,other,94043
2,3,23,M,writer,32067
3,4,24,M,technician,43537
4,5,33,F,other,15213
...,...,...,...,...,...
938,939,26,F,student,33319
939,940,32,M,administrator,02215
940,941,20,M,student,97229
941,942,48,F,librarian,78209


### Step 4. See the first 25 entries

In [34]:
df.head(25)

,user_id,age,gender,occupation,zip_code
0,1,24,M,technician,85711
1,2,53,F,other,94043
2,3,23,M,writer,32067
3,4,24,M,technician,43537
4,5,33,F,other,15213
5,6,42,M,executive,98101
6,7,57,M,administrator,91344
7,8,36,M,administrator,05201
8,9,29,M,student,01002
9,10,53,M,lawyer,90703


### Step 5. See the last 10 entries

In [35]:
df.tail(10)

,user_id,age,gender,occupation,zip_code
933,934,61,M,engineer,22902
934,935,42,M,doctor,66221
935,936,24,M,other,32789
936,937,48,M,educator,98072
937,938,38,F,technician,55038
938,939,26,F,student,33319
939,940,32,M,administrator,02215
940,941,20,M,student,97229
941,942,48,F,librarian,78209
942,943,22,M,student,77841


### Step 6. What is the number of observations in the dataset?

In [36]:
df.shape

(943, 5)

### Step 7. What is the number of columns in the dataset?

In [37]:
df.shape[1]

5

### Step 8. Print the name of all the columns.

In [38]:
df.columns

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [39]:
# "the index" (aka "the labels")
df.index

RangeIndex(start=0, stop=943, step=1)

### Step 10. What is the data type of each column?

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   user_id     943 non-null    int64 
 1   age         943 non-null    int64 
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB


### Step 11. Print only the occupation column

In [42]:
df['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...      
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [43]:
df['occupation'].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

### Step 13. What is the most frequent occupation?

In [44]:
df["occupation"].value_counts().head(5)

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [45]:
df.describe()

,user_id,age
count,943.000000,943.000000
mean,472.000000,34.051962
std,272.364951,12.192740
min,1.000000,7.000000
25%,236.500000,25.000000
50%,472.000000,31.000000
75%,707.500000,43.000000
max,943.000000,73.000000


### Step 15. Summarize all the columns

In [46]:
df.describe(include="all")

,user_id,age,gender,occupation,zip_code
count,943.000000,943.000000,943,943,943
unique,NaN,NaN,2,21,795
top,NaN,NaN,M,student,55414
freq,NaN,NaN,670,196,9
mean,472.000000,34.051962,NaN,NaN,NaN
std,272.364951,12.192740,NaN,NaN,NaN
min,1.000000,7.000000,NaN,NaN,NaN
25%,236.500000,25.000000,NaN,NaN,NaN
50%,472.000000,31.000000,NaN,NaN,NaN
75%,707.500000,43.000000,NaN,NaN,NaN


### Step 16. Summarize only the occupation column

In [47]:
df["occupation"].describe(include = "object")

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [48]:
df['age'].mean()

np.float64(34.05196182396607)

### Step 18. What is the age with least occurrence?

In [49]:
df['age'].min()

7